# Generated by Django 6.0.3 on 2026-04-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за кг ($/сом)')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('in_transit', 'В пути'), ('received', 'Получено (в РФ)'), ('issued', 'Выдано клиенту')], default='sent', max_length=20, verbose_name='Статус')),
                ('shipping_date', models.DateField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-shipping_date', '-id'],
            },
        ),
    ]
