# Generated by Django 6.0.3 on 2026-04-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_shipmentstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='category',
            field=models.CharField(choices=[('clothes', 'Одежда'), ('shoes', 'Обувь'), ('electronics', 'Электроника'), ('household', 'Бытовая техника'), ('cosmetics', 'Косметика'), ('food', 'Продукты питания'), ('documents', 'Документы'), ('medicine', 'Медикаменты'), ('toys', 'Игрушки'), ('books', 'Книги'), ('furniture', 'Мебель'), ('auto_parts', 'Автозапчасти'), ('building', 'Стройматериалы'), ('textiles', 'Текстиль'), ('accessories', 'Аксессуары'), ('sports', 'Спорттовары'), ('fragile', 'Хрупкое'), ('oversized', 'Негабаритный'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Категория'),
        ),
    ]
