# Generated by Django 6.0.3 on 2026-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_shipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='waybill_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер накладной'),
        ),
    ]
