# Generated by Django 6.0.3 on 2026-04-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_shipment_waybill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номенклатура')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Сумма')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='logistics.shipment', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Дополнительный расход',
                'verbose_name_plural': 'Дополнительные расходы',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Услуга по доставке товара', max_length=200, verbose_name='Наименование услуги')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование товара клиента')),
                ('places_count', models.PositiveIntegerField(default=1, verbose_name='Количество мест')),
                ('units_count', models.PositiveIntegerField(default=1, verbose_name='Количество шт.')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общий вес, кг')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуги')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Сумма')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.shipment', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
