# Generated by Django 5.2 on 2026-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_shipmentexpense_shipmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Город назначения'),
        ),
    ]
