# Generated by Django 5.2 on 2026-04-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_pricetier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetier',
            options={'ordering': ['min_weight', 'max_weight'], 'verbose_name': 'Тариф по весу', 'verbose_name_plural': 'Тарифы по весу'},
        ),
        migrations.AddField(
            model_name='pricetier',
            name='is_per_kg',
            field=models.BooleanField(default=False, help_text='Если включено — цена × вес. Иначе — фиксированная сумма.', verbose_name='За каждый кг'),
        ),
        migrations.AddField(
            model_name='pricetier',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='От (кг)'),
        ),
        migrations.AddField(
            model_name='pricetier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (сом)'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='is_fixed_price',
            field=models.BooleanField(default=False, verbose_name='Фиксированная цена'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Оставьте пустым для последнего тарифа (∞)', max_digits=10, null=True, verbose_name='До (кг)'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за кг (устар.)'),
        ),
    ]
