# Generated by Django 5.2 on 2026-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='г. Бишкек', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='organization',
            field=models.CharField(default='KG Cargo', max_length=200, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+996 XXX XXX XXX', max_length=30, verbose_name='Телефон'),
        ),
    ]
