# Generated by Django 5.2 on 2026-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sitesettings_address_sitesettings_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='organization',
            field=models.CharField(default='MowExpress', max_length=200, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='MowExpress', max_length=100, verbose_name='Название сайта'),
        ),
    ]
