version: '3.8'

services:
  db_kgcargo:
    image: postgres:14
    container_name: postgres_db_kgcargo
    env_file:
      - ../.env
    volumes:
      - postgres_data_kgcargo:/var/lib/postgresql/data
    networks:
      - portfolio_network_kgcargo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_kgcargo:
    image: redis:6
    container_name: redis_kgcargo
    networks:
      - portfolio_network_kgcargo

  web_kgcargo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_kgcargo
    command: sh -c "/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    depends_on:
      db_kgcargo:
        condition: service_healthy
      redis_kgcargo:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - portfolio_network_kgcargo

networks:
  portfolio_network_kgcargo:
    driver: bridge

volumes:
  postgres_data_kgcargo:
